modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/Juuxel/Adorn/issues"

[[mods]]
modId = "adorn"
version = "${version}"
displayName = "Adorn"
description = "Decorate your home!"
authors = "Juuz"
logoFile = "icon.png"

[[mixins]]
config = "mixins.adorn.common.json"

[[mixins]]
config = "mixins.adorn.forge.json"

[[dependencies.adorn]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,1.21)"

[[dependencies.adorn]]
modId = "neoforge"
mandatory = true
versionRange="[20.4.27-beta,)"
