modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/Juuxel/Adorn/issues"

[[mods]]
modId = "adorn"
version = "${version}"
displayName = "Adorn"
description = "Decorate your home!"
authors = "Juuz"
logoFile = "assets/adorn/icon.png"
logoBlur = false

[[mixins]]
config = "mixins.adorn.common.json"

[[mixins]]
config = "mixins.adorn.neo.json"

[[dependencies.adorn]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,26.2)"

[[dependencies.adorn]]
modId = "neoforge"
type = "required"
versionRange="[26.1.0.19-beta,)"
