org.gradle.jvmargs=-Xmx3G -XX:+UseG1GC
# Enable parallel task execution, this makes a multiproject
# a bit faster.
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Adorn
mod-version = 7.3.1

# Minecraft
minecraft-version = 1.21.9
yarn-mappings = build.1
menu-mappings = 1.21.8+1
neoforge-mappings-patch-version = 1.21+build.4
