org.gradle.jvmargs=-Xmx3G -XX:+UseG1GC
# Enable parallel task execution, this makes a multiproject
# a bit faster.
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=true

# Adorn
mod-version = 9.0.0
group = io.github.juuxel
archives-name = Adorn

# Minecraft
minecraft-version = 26.2
