org.gradle.jvmargs=-Xmx3G -XX:+UseG1GC
# Enable parallel task execution, this makes a multiproject
# a bit faster.
org.gradle.parallel=true

# Adorn
mod-version = 6.0.2

# Minecraft
minecraft-version = 1.21.1
yarn-mappings = build.3
menu-mappings = 1.19.3+1
neoforge-mappings-patch-version = 1.21+build.4
