[versions]
emi = "1.1.10+1.21"
fabric-loader = "0.19.3"
fabric-api = "0.141.4+1.21.11"
jankson = "1.2.1"
modmenu = "17.0.0"
neoforge = "21.11.42"
rei = "21.11.816"
towelette = "e5e39eb"

[libraries]
# Loader dependencies
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

# Non-mod library dependencies
jankson = { module = "blue.endless:jankson", version.ref = "jankson" }

# Mod dependencies
emi-common = { module = "dev.emi:emi-xplat-intermediary", version.ref = "emi" }
emi-fabric = { module = "dev.emi:emi-fabric", version.ref = "emi" }
emi-forge = { module = "dev.emi:emi-forge", version.ref = "emi" }
jei-fabric = { module = "maven.modrinth:jei", version = "ev0nR76F" }
jei-forge = { module = "maven.modrinth:jei", version = "4GyeMvGn" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
rei-annotations = { module = "me.shedaniel:REIPluginCompatibilities-forge-annotations", version = "12.0.54" }
rei-common = { module = "me.shedaniel:RoughlyEnoughItems-api", version.ref = "rei" }
rei-neoforge = { module = "me.shedaniel:RoughlyEnoughItems-api-neoforge", version.ref = "rei" }
rei-fabric = { module = "me.shedaniel:RoughlyEnoughItems-fabric", version.ref = "rei" }
towelette = { module = "com.github.Virtuoel:Towelette", version.ref = "towelette" }
