package juuxel.adorn.compat

import juuxel.adorn.api.block.BlockVariant

object BlockusCompat : BlockVariantSet {
    override val woodVariants = listOf(BlockVariant.Wood("blockus/white_oak"))
    override val stoneVariants = listOf(
        "andesite_brick",
        "black_stone_brick",
        "blaze_brick",
        "blue_stone_brick",
        "bluestone_brick",
        "bluestone_tile",
        "bluestone",
        "brown_stone_brick",
        "charred_brick",
        "charred_nether_brick",
        "crimson_warty_blackstone_brick",
        "cyan_stone_brick",
        "diorite_brick",
        "dripstone_brick",
        "gray_stone_brick",
        "green_stone_brick",
        "honeycomb_brick",
        "ice_brick",
        "large_brick",
        "lava_brick",
        "lava_polished_blackstone",
        "light_blue_stone_brick",
        "lime_stone_brick",
        "limestone_brick",
        "limestone_tile",
        "limestone",
        "magenta_stone_brick",
        "magma_brick",
        "marble_brick",
        "marble_tile",
        "marble",
        "mossy_deepslate_brick",
        "netherrack_brick",
        "obsidian_brick",
        "orange_stone_brick",
        "phantom_purpur_brick",
        "pink_stone_brick",
        "polished_basalt_brick",
        "purple_stone_brick",
        "purpur_brick",
        "quartz_tile",
        "red_sandstone_brick",
        "red_stone_brick",
        "sandstone_brick",
        "sandy_brick",
        "small_bluestone_brick",
        "small_end_stone_brick",
        "small_limestone_brick",
        "small_magma_brick",
        "small_marble_brick",
        "small_obsidian_brick",
        "small_phantom_purpur_brick",
        "small_purpur_brick",
        "small_red_sandstone_brick",
        "small_sandstone_brick",
        "small_soul_sandstone_brick",
        "snow_brick",
        "soaked_brick",
        "soul_sandstone_brick",
        "soul_sandstone",
        "teal_nether_brick",
        "tuff_brick",
        "water_brick",
        "warped_warty_blackstone_brick",
        "white_stone_brick",
        "yellow_stone_brick",
    ).map { BlockVariant.Stone("blockus/$it") }
}
